version: "3.8"

services:
  web:
    build: ./src
    container_name: "${APP_NAME}_web"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/src/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mysite-network

  db:
    image: postgres:16
    container_name: "${APP_NAME}_db"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mysite
      - PGTZ='Asia/Kolkata'
    networks:
      - mysite-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: "${APP_NAME}_pgadmin"
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mysite-network
  
  mailpit:
    image: "axllent/mailpit:latest"
    container_name: "${APP_NAME}_mailpit"
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit_data:/data
    networks:
      - mysite-network
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgres_data:
  pgadmin_data:
  mailpit_data:

networks:
  mysite-network: